dataset: oasis
arch: unireg_rpn
compute_size: [192, 224, 160]
use_pre_align: false

task_type: inter-subject
task_type_id: 0
task_id: brain
task_id_id: 5

pair_json: ${DATA_ROOT}/OASIS/LUMIR_train_OASIS_val_test500.json

train_root: ${DATA_ROOT}/LUMIR/imagesTr
train_seg_root:

val_root: ${DATA_ROOT}/OASIS/imagesTr
val_seg_root: ${DATA_ROOT}/OASIS/labelsTr
val_mask_root: ${DATA_ROOT}/OASIS/masksTr

test_root: ${DATA_ROOT}/OASIS/imagesTr
test_seg_root: ${DATA_ROOT}/OASIS/labelsTr
test_mask_root: ${DATA_ROOT}/OASIS/masksTr

sim_loss: ncc
ncc_win: 9
sim_weight: 1.0
reg_loss: grad_l2
reg_weight: 1.0

batch_size: 1
num_workers: 4
amp: true
eval_in_raw: false