dataset: head_unified
arch: unireg_rpn
compute_size: [160, 192, 192]
use_pre_align: true

task_type: inter-subject
task_type_id: 0
task_id: head
task_id_id: 2

sim_loss: ncc
ncc_win: 9
sim_weight: 1.0
reg_loss: grad_l2
reg_weight: 1.0

batch_size: 1
num_workers: 4
amp: true
eval_in_raw: false
seed: 42
